auditlog:
  dir: c:/tmp
  file: testauditfile.log

project:
  version: @project.version@
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    favicon:
      enabled: false
  security:
    user:
      name: user
      password: password
  ldap:
    urls: ldap://eid-systest-ldap01.dmz.local:389
    username: cn=directory manager
    password: password
    base: dc=norge,dc=no
    maxConnections: 10
    maxWait: 5000
    serviceproviderBase: ou=serviceproviders,dc=idporten,dc=no

management:
  health:
    defaults:
      enabled: false
    ldap:
      enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: "version, health, info"
  endpoint:
    health:
      show-details: always
      enabled: true

idporten:
  redirecturl: http://localhost:8080/redirecturl
  serviceprovider:
    default-name: Ukjent tjenesteeier
minid-plus:
  token-lifetime-seconds: 600
  code-lifetime-seconds: 600 #60 default
  credential-error-max-number: 3
  quarantine-counter-max-number: 3
  serverid:
  logging:
    categoryname: minidplus
  cache:
    otp-ttl-in-s: 600
  registrationUri:
    https://eid-systest-static-web01
  context-path:"/"
event:
  jmsUrl: tcp://eid-systest-admin01.dmz.local:61616
  jmsQueue: logqueue
# LINKMobility integration
linkmobility:
  url: https://gw2-fro.pswin.com:8443
  account: difi-test
  password: F82iS5A7X
  connectTimeout: 5000 #ms?
  readTimeout: 10000 #ms?
  sender: Digdir
  ttl: 600 #s

# Email
email:
  url: http://eid-systest-admin01.dmz.local:10002/kontaktinfo-backend/rest/notifyUser/
  connectTimeout: 5000
  readTimeout: 10000

server:
  tomcat:
    additional-tld-skip-patterns: xercesImpl.jar,xml-apis.jar,serializer.jar,xml-apis.jar
    protocol-header: x-forwarded-proto
  servlet:
    session:
      cookie:
        http-only: true
  forward-headers-strategy: native
