project:
  version: @project.version@
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    favicon:
      enabled: false
  security:
    user:
      name: user
      password: password

management:
  health:
    diskspace:
      enabled: false
  endpoints:
    web:
      base-path: /
      exposure:
        include: "version, health, info"
  endpoint:
    health:
      show-details: always
      enabled: true

idporten:
  redirecturl: http://localhost:8080/redirecturl

minid-plus:
  logging:
    categoryname: minidplus
