auditlog:
  dir: c:/tmp
  file: testauditfile.log

project:
  version: @project.version@
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    favicon:
      enabled: false
  security:
    user:
      name: openam
      password: clientsecret
  ldap:
    urls: ldap://eid-systest-ldap01.dmz.local:389
    username: cn=directory manager
    password: password
    base: dc=norge,dc=no
    maxConnections: 10
    maxWait: 5000
    serviceproviderBase: ou=serviceproviders,dc=idporten,dc=no
  mail:
    host: lekex1.domain.local
    port: 25
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        debug: false
        smtp:
          from: noreply@digdir.no
          to:
            smoketest: utvtest@digdir.no
          auth: false
          connectiontimeout: 5000
          writetimeout: 2000
          starttls:
            enable: false

management:
  health:
    defaults:
      enabled: false
    ldap:
      enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: "version, health, info"
  endpoint:
    health:
      show-details: always
      enabled: true

idporten:
  redirecturl: http://localhost:8080/redirecturl
  serviceprovider:
    default-name: Ukjent tjenesteeier
minid-plus:
  token-lifetime-seconds: 600
  code-lifetime-seconds: 600 #60 default
  credential-error-max-number: 3
  quarantine-counter-max-number: 3
  serverid:
  logging:
    categoryname: minidplus
  cache:
    otp-ttl-in-s: 600
    session-ttl-in-s: 1800
  registrationUri:
    https://eid-systest-static-web01
  callback-method-post: true
  # nb: set to .* in production
  mail:
    allowed-filter: '.*digdir\.no|.*hostingtjenester\.no'
  sms-filter:
    enabled: true
    filename: difi-mobile-numbers.txt
event:
  jmsUrl: tcp://eid-systest-admin01.dmz.local:61616
  jmsQueue: logqueue
# LINKMobility integration
linkmobility:
  url: https://gw2-fro.pswin.com:8443
  account: difi-test
  password: F82iS5A7X
  connectTimeout: 5000 #ms?
  readTimeout: 10000 #ms?
  sender: Digdir
  ttl: 600 #s

server:
  tomcat:
    additional-tld-skip-patterns: xercesImpl.jar,xml-apis.jar,serializer.jar,xml-apis.jar
    protocol-header: x-forwarded-proto
  servlet:
    session:
      timeout: 1800s
      cookie:
        http-only: true
  forward-headers-strategy: native

jwt:
  keystore:
    type: JKS
    location: classpath:./minidauth-env.jks
    password: changeit
    key_alias: minidauth
    key_password: changeit

oidc-sdk:
#  issuer: https://eid-atest-web01.dmz.local:443/minidplus-authentication/v2
  issuer: http://localhost:8080/v2
  clients:
    -
      client-id: openam
      client-secret: clientsecret
      scopes:
        - openid
        - profile
      redirect-uris:
        - https://eid-atest-web01.dmz.local:443/opensso/UI/Login?realm=norge.no
    -
      client-id: testclient
      client-secret: password
      scopes:
        - openid
        - profile
      redirect-uris:
        - http://localhost:8888/idporten-oidc-client/authorize/response
