version: '3.3'

services:
  minidplus-authentication:
    image: ${REGISTRY}/minidplus-authentication:${VERSION}
    extra_hosts:
      - "eid-elk-app01.dmz.local:10.243.220.21"
    configs:
      - log_config
    ports:
      - 8080
    networks:
      atest:
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.atest == true
  web:
    image: eid-jenkins02.dmz.local:8081/web:latest
    extra_hosts:
      - "eid-elk-app01.dmz.local:10.243.220.21"
    configs:
      - log_config
    ports:
      - 443:443
    networks:
      atest:
        aliases:
          - eid-atest-web01.dmz.local
          - eid-inttest-web01.dmz.local
    dns: 8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.atest == true

networks:
  atest:
    driver: overlay
    attachable: true
configs:
  log_config:
    file: ./log_config
